---
title: "Notes"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes on `rlang`


```{r}
x = 2
y = 3
# the expression that is passed is the value
rlang::expr(x + y)

# the evaluation of the expression that is passed is the value
# rlang::enexpr(x + y) # fails since it must be a symbol
rlang::enexpr(x)
rlang::enexpr(y)
```

```{r}
x = 2
y = 3

rlang::quo(x) %>% rlang::eval_tidy()
rlang::enquo(x) %>% rlang::eval_tidy()
```


```{r quo}
# quosures capture an expr AND an environment
library(tibble)
tbl = tibble(x = 1:3,y = x + 1)

f = function(tbl,x) {
  x = rlang::enquo(x)
  print(x)
  tbl %>% dplyr::mutate(x = !!x)
}

x = 5
y = 6
z = 7
tbl %>% f(4)
tbl %>% f(x) # x is present in tbl, does not look anywhere else
tbl %>% f(!!x) # this looks like 5 
tbl %>% f(z) # z is not present in tbl, so the value of z is used
tbl %>% f(!!z) # this looks like 7
tbl %>% f(x + 4)
tbl %>% f(x + y + z) 
tbl %>% f(!!x + y) # this looks like 5 + y
tbl %>% f(x + !!y) 
tbl %>% f(!!x + !!y) 
tbl %>% f(mean(y)) # formulas
```

```{r expr}
# expressions capture expressions
library(tibble)
tbl = tibble(x = 1:3,y = x + 1)

f = function(tbl,x) {
  x = rlang::enexpr(x)
  print(x)
  print(length(x))
  print(class(x))
  print(names(x))
  tbl %>% dplyr::mutate(x = !!x)
}

x = 5
y = 6
z = 7
tbl %>% f(4)
tbl %>% f(x) # x is present in tbl, does not look anywhere else
tbl %>% f(!!x) # this looks like 5 
tbl %>% f(z) # z is not present in tbl, so the value of z is used
tbl %>% f(!!z) # this looks like 7
tbl %>% f(x + 4)
tbl %>% f(x + y + z) 
tbl %>% f(!!x + y) # this looks like 5 + y
tbl %>% f(x + !!y) 
tbl %>% f(!!x + !!y) 
tbl %>% f(mean(y)) # formulas
```

```{r sym}
# expressions capture expressions
library(tibble)
tbl = tibble(x = 1:3,y = x + 1)

f = function(tbl,x) {
  x = rlang::ensym(x)
  print(x)
  tbl %>% dplyr::mutate(x = !!x)
}

x = 5
y = 6
z = 7
tbl %>% f(y) # permitts only symbols
tbl %>% f(4)
tbl %>% f(!!x)
tbl %>% f(x + 4)
tbl %>% f(x + y + z) 
tbl %>% f(!!x + y) # this looks like 5 + y
tbl %>% f(x + !!y)
tbl %>% f(!!x + !!y) 
tbl %>% f(mean(y)) # formulas
```


```{r}
library(tibble)
tbl = tibble(x = 1:3,y = x + 1)

f = function(.data,...) {
  dots = rlang::enquos(...)
  print(dots)
  
  for (i in seq_along(dots)) {
    name = names(dots)[[i]]
    dot = dots[[i]]
    
    .data[[name]] = rlang::eval_tidy(dot,.data)
  }
  
  .data
}

x = 5
y = 6
z = 7
tbl %>% f(4)
tbl %>% f(!!x)
tbl %>% f(x + 4)
tbl %>% f(x + y + z) 
tbl %>% f(!!x + y) # this looks like 5 + y
tbl %>% f(x + !!y)
tbl %>% f(!!x + !!y) 
tbl %>% f(mean(y)) # formulas
```
