```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
  )
```

# Cube Geoms

## `geom_unit_cube` {-}

### usage {-}

```{r geom_unit_cube single}
library(tibble)
library(dplyr)
library(ggplot2)
library(ggshapes)

ggplot() +
  xlim(-2,2) +
  ylim(-2,2) +
  coord_equal() +
  geom_unit_cube(mapping = aes(xc = 0, yc = 0), fill = 'skyblue3')
```

```{r geom_unit_cube multiple}
# create a scene
tribble(
  ~xc  , ~yc  , ~fill     ,
  0    , 0    , 'skyblue3',
  0.5  , 1    , 'orange3' ,
  1    , -1   , 'purple3' ,
) -> tbl_cubes

ggplot() +
  xlim(-2,2) +
  ylim(-2,2) +
  coord_equal() +
  geom_unit_cube(data = tbl_cubes,
                 mapping = aes(xc = xc, yc = yc))
```

### gotchas {-}

- [ ] `fill` parameter should permit colors to be assigned to each rows

## `geom_cuboid` {-}

### usage {-}

```{r geom_cuboid single}
library(tibble)
library(dplyr)
library(ggplot2)
library(ggshapes)

ggplot() +
  xlim(-2,2) +
  ylim(-2,2) +
  coord_equal() +
  geom_cuboid(mapping = aes(xc = 0, yc = 0,
                            lx = 3, ly = 2, lz = 1),
              fill = 'skyblue3')
```

```{r geom_cuboid multiple}
# create a scene
tribble(
  ~xc  , ~yc  , ~lx , ~ly , ~lz , ~fill     ,
  0    , 0    , 1   , 1   , 1   , 'skyblue3',
  0.5  , 1    , 1   , 2   , 3   , 'orange3' ,
  1    , -1   , 3   , 2   , 1   , 'purple3' ,
) -> tbl_cuboids

ggplot() +
  xlim(-4,4) +
  ylim(-4,4) +
  coord_equal() +
  geom_cuboid(data = tbl_cuboids,
                 mapping = aes(xc = xc, yc = yc,
                               lx = lx, ly = ly, lz = lz))
```

### gotchas {-}

- [ ] `fill` parameter should permit colors to be assigned to each rows

## `geom_cuboid_slice` {-}

### usage {-}

```{r geom_cuboid_slice single}
library(tibble)
library(dplyr)
library(ggplot2)
library(ggshapes)

ggplot() +
  xlim(-4,4) +
  ylim(-4,4) +
  coord_equal() +
  geom_cuboid_slice(mapping = aes(xc = 0, yc = 0,
                                  lx = 1, ly = 1, lz = 1,
                                  sx = .5, sxend = 1,
                                  sy = .5, syend = 1,
                                  sz =  0, szend = 1),
                    fill = 'skyblue3') +
  geom_cuboid(mapping = aes(xc = 0, yc = 0,
                            lx = 1, ly = 1, lz = 1),
                  fill = 'NA')
```

### bugs {-}

- [ ] does not correctly place slice inside of cuboid due to early form not using bounding box

