```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
  )
```


# Matrix Geoms

## `geom_matrix` {-}

### usage

```{r geom_matrix single}
library(tibble)
library(dplyr)
library(ggplot2)
library(ggshapes)

ggplot() + 
  xlim(-2,2) +
  ylim(-2,2) +
  coord_equal() +
  geom_matrix(mapping = aes(xc = 0, yc = 0,
                            lx = 3, ly = 2, lz = 1), 
              viewx = 2, viewy = 2,
              fill = 'skyblue3')
```

```{r geom_matrix multiple}
# create a scene
# create a scene
tribble(
  ~xc  , ~yc  , ~lx , ~ly , ~lz , ~fill     ,
  0    , 0    , 1   , 1   , 1   , 'skyblue3',  
  0.5  , 1    , 1   , 2   , 3   , 'orange3' ,  
  1    , -1   , 3   , 2   , 1   , 'purple3' ,  
) %>% dplyr::slice(3) -> tbl_matrices

ggplot() + 
  xlim(-2,2) +
  ylim(-2,2) +
  coord_equal() +
  geom_matrix(data = tbl_matrices,
                 mapping = aes(xc = xc, yc = yc, 
                               lx = lx, ly = ly, lz = lz))
```

### bugs {-}

- [ ] does not permit 1 row : 1 matrix
- [ ] does not properly center the matrix at 0, 0
- [ ] `fill` parameter should permit colors to be assigned to each rows
